name: PremiumParticles
version: 13.37
author: codex01 ~ Jonas

main: de.codex01.pp.Main

commands:
     moveeffect:
          description: Aktiviert einen Moveeffect.
          permissions: pp.moveeffect
          aliases: meffect
     bowtrail:
          description: Aktiviert einen Bowtrail.
          permissions: pp.bowtrail
          aliases: btrail
     premiumparticles:
          description: Basic command for admin stuff.
          aliases: pp